// SPDX-License-Identifier: MIT
//
// Niri -> KWin 6 (Plasma 6) compatibility shim -- GLES / legacy profile.
// Auto-generated by build/generate.py. Do not edit by hand; edit the generator.

#include "colormanagement.glsl"

uniform sampler2D sampler;
uniform int textureWidth;
uniform int textureHeight;

uniform bool  uForOpening;
uniform float uProgress;

varying vec2 texcoord0;

float niri_ease(float t) { float f = t - 1.0; return f * f * f + 1.0; }

#define niri_clamped_progress clamp(niri_ease(uProgress), 0.0, 1.0)
#define niri_random_seed      uSeed
#define niri_tex              sampler

const mat3 niri_geo_to_tex = mat3(1.0, 0.0, 0.0,
                                  0.0, -1.0, 0.0,
                                  0.0, 1.0, 1.0);

// --------------------------------------------------------------------- Niri body

            // Ported from skwd-wall plasma-flow transition

            float pf_hash(vec2 p) {
                return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
            }

            float pf_noise(vec2 p) {
                vec2 i = floor(p);
                vec2 f = fract(p);
                f = f * f * (3.0 - 2.0 * f);
                return mix(mix(pf_hash(i), pf_hash(i + vec2(1.0, 0.0)), f.x),
                           mix(pf_hash(i + vec2(0.0, 1.0)), pf_hash(i + vec2(1.0, 1.0)), f.x), f.y);
            }

            vec4 open_color(vec3 coords_geo, vec3 size_geo) {
                float p = niri_clamped_progress;
                vec2 uv = coords_geo.xy;

                vec2 flow = vec2(
                    pf_noise(uv * 5.0 + vec2(p * 2.0, 0.0)),
                    pf_noise(uv * 5.0 + vec2(0.0, p * 2.0))
                ) - 0.5;
                float intensity = sin(p * 3.14159) * 0.18;
                vec2 distorted = uv + flow * intensity;

                vec3 tc = niri_geo_to_tex * vec3(distorted, 1.0);
                vec4 win = texture2D(niri_tex, tc.st);

                float reveal = smoothstep(0.2, 0.8, p);
                return win * reveal;
            }


            vec4 close_color(vec3 coords_geo, vec3 size_geo) {
                float p = 1.0 - niri_clamped_progress;
                vec2 uv = coords_geo.xy;

                vec2 flow = vec2(
                    pf_noise(uv * 5.0 + vec2(p * 2.0, 0.0)),
                    pf_noise(uv * 5.0 + vec2(0.0, p * 2.0))
                ) - 0.5;
                float intensity = sin(p * 3.14159) * 0.18;
                vec2 distorted = uv + flow * intensity;

                vec3 tc = niri_geo_to_tex * vec3(distorted, 1.0);
                vec4 win = texture2D(niri_tex, tc.st);

                float reveal = smoothstep(0.2, 0.8, p);
                return win * reveal;
            }

// -------------------------------------------------------------------- entry point
void main() {
  vec3 coords_geo = vec3(texcoord0.x, 1.0 - texcoord0.y, 0.0);
  vec3 size_geo   = vec3(float(textureWidth), float(textureHeight), 1.0);

  vec4 c = uForOpening ? open_color(coords_geo, size_geo)
                       : close_color(coords_geo, size_geo);

  c = sourceEncodingToNitsInDestinationColorspace(c);
  c = nitsToDestinationEncoding(c);
  gl_FragColor = c;
}
