#version 140

// SPDX-License-Identifier: MIT
//
// Niri -> KWin 6 (Plasma 6) compatibility shim -- desktop GL core profile.
// Auto-generated by build/generate.py. Do not edit by hand; edit the generator.
//
// The Niri open_color()/close_color() body below is used verbatim. This prelude
// emulates the Niri built-ins it references.

#include "colormanagement.glsl"

uniform sampler2D sampler;
uniform int textureWidth;
uniform int textureHeight;

uniform bool  uForOpening;   // true while a window-open animation runs
uniform float uProgress;     // linear 0 -> 1 over the animation

in vec2 texcoord0;
out vec4 fragColor;

// The Niri bodies call texture2D(); route it to the core-profile entry point.
#define texture2D texture

// KWin animates uProgress linearly; Niri feeds an already-eased progress. The
// Niri configs for the ported effects all use curve "ease-out-cubic".
float niri_ease(float t) { float f = t - 1.0; return f * f * f + 1.0; }

#define niri_clamped_progress clamp(niri_ease(uProgress), 0.0, 1.0)
#define niri_random_seed      uSeed
#define niri_tex              sampler

// Niri window UVs have a top-left origin; KWin's texcoord0 is bottom-left. This
// matrix maps a top-left (x, y) to the sampler coordinate (x, 1 - y), so the
// Niri expression texture2D(niri_tex, (niri_geo_to_tex * vec3(uv,1)).st) samples
// the window at the top-left UV `uv`.
const mat3 niri_geo_to_tex = mat3(1.0, 0.0, 0.0,
                                  0.0, -1.0, 0.0,
                                  0.0, 1.0, 1.0);

// --------------------------------------------------------------------- Niri body
            vec4 open_color(vec3 coords_geo, vec3 size_geo) {
                float p = niri_clamped_progress;
                vec2 uv = coords_geo.xy;

                vec2 center = vec2(0.5, 0.5);
                float scale = mix(0.95, 1.0, p);
                vec2 scaled_uv = (uv - center) / scale + center;

                vec3 tex_coords = niri_geo_to_tex * vec3(scaled_uv, 1.0);
                vec4 color = texture2D(niri_tex, tex_coords.st);

                float alpha = smoothstep(0.0, 0.8, p);

                return color * alpha;
            }

            vec4 close_color(vec3 coords_geo, vec3 size_geo) {
                float p = niri_clamped_progress;
                vec2 uv = coords_geo.xy;

                vec2 center = vec2(0.5, 0.5);
                float scale = mix(1.0, 0.95, p);
                vec2 scaled_uv = (uv - center) / scale + center;

                vec3 tex_coords = niri_geo_to_tex * vec3(scaled_uv, 1.0);
                vec4 color = texture2D(niri_tex, tex_coords.st);

                float alpha = smoothstep(1.0, 0.2, p);

                return color * alpha;
            }

// -------------------------------------------------------------------- entry point
void main() {
  vec3 coords_geo = vec3(texcoord0.x, 1.0 - texcoord0.y, 0.0);
  vec3 size_geo   = vec3(float(textureWidth), float(textureHeight), 1.0);

  vec4 c = uForOpening ? open_color(coords_geo, size_geo)
                       : close_color(coords_geo, size_geo);

  // Niri returns premultiplied-alpha color -- exactly what KWin expects.
  fragColor = c;
  fragColor = sourceEncodingToNitsInDestinationColorspace(fragColor);
  fragColor = nitsToDestinationEncoding(fragColor);
}
