// SPDX-License-Identifier: MIT
//
// Niri -> KWin 6 (Plasma 6) compatibility shim -- GLES / legacy profile.
// Auto-generated by build/generate.py. Do not edit by hand; edit the generator.

#include "colormanagement.glsl"

uniform sampler2D sampler;
uniform int textureWidth;
uniform int textureHeight;

uniform bool  uForOpening;
uniform float uProgress;

varying vec2 texcoord0;

float niri_ease(float t) { float f = t - 1.0; return f * f * f + 1.0; }

#define niri_clamped_progress clamp(niri_ease(uProgress), 0.0, 1.0)
#define niri_random_seed      uSeed
#define niri_tex              sampler

const mat3 niri_geo_to_tex = mat3(1.0, 0.0, 0.0,
                                  0.0, -1.0, 0.0,
                                  0.0, 1.0, 1.0);

// --------------------------------------------------------------------- Niri body

            // Ported from skwd-wall crosshatch transition

            float crosshatch_rand(vec2 co) {
                return fract(sin(dot(co.xy, vec2(12.9898, 78.233))) * 43758.5453);
            }

            vec4 open_color(vec3 coords_geo, vec3 size_geo) {
                float p = niri_clamped_progress;
                vec2 uv = coords_geo.xy;
                vec3 tc = niri_geo_to_tex * vec3(uv, 1.0);
                vec4 win = texture2D(niri_tex, tc.st);

                vec2 center = vec2(0.5);
                float threshold = 3.0;
                float fadeEdge = 0.1;
                float dist = distance(center, uv) / threshold;
                float r = p - min(crosshatch_rand(vec2(uv.y, 0.0)), crosshatch_rand(vec2(0.0, uv.x)));
                float reveal = mix(0.0, mix(step(dist, r), 1.0, smoothstep(1.0 - fadeEdge, 1.0, p)), smoothstep(0.0, fadeEdge, p));

                return win * reveal;
            }


            vec4 close_color(vec3 coords_geo, vec3 size_geo) {
                float p = 1.0 - niri_clamped_progress;
                vec2 uv = coords_geo.xy;
                vec3 tc = niri_geo_to_tex * vec3(uv, 1.0);
                vec4 win = texture2D(niri_tex, tc.st);

                vec2 center = vec2(0.5);
                float threshold = 3.0;
                float fadeEdge = 0.1;
                float dist = distance(center, uv) / threshold;
                float r = p - min(crosshatch_rand(vec2(uv.y, 0.0)), crosshatch_rand(vec2(0.0, uv.x)));
                float reveal = mix(0.0, mix(step(dist, r), 1.0, smoothstep(1.0 - fadeEdge, 1.0, p)), smoothstep(0.0, fadeEdge, p));

                return win * reveal;
            }

// -------------------------------------------------------------------- entry point
void main() {
  vec3 coords_geo = vec3(texcoord0.x, 1.0 - texcoord0.y, 0.0);
  vec3 size_geo   = vec3(float(textureWidth), float(textureHeight), 1.0);

  vec4 c = uForOpening ? open_color(coords_geo, size_geo)
                       : close_color(coords_geo, size_geo);

  c = sourceEncodingToNitsInDestinationColorspace(c);
  c = nitsToDestinationEncoding(c);
  gl_FragColor = c;
}
