#version 140

// SPDX-License-Identifier: MIT
//
// Niri -> KWin 6 (Plasma 6) compatibility shim -- desktop GL core profile.
// Auto-generated by build/generate.py. Do not edit by hand; edit the generator.
//
// The Niri open_color()/close_color() body below is used verbatim. This prelude
// emulates the Niri built-ins it references.

#include "colormanagement.glsl"

uniform sampler2D sampler;
uniform int textureWidth;
uniform int textureHeight;

uniform bool  uForOpening;   // true while a window-open animation runs
uniform float uProgress;     // linear 0 -> 1 over the animation
uniform float uSeed;      // per-animation random phase, [0, 1)

in vec2 texcoord0;
out vec4 fragColor;

// The Niri bodies call texture2D(); route it to the core-profile entry point.
#define texture2D texture

// KWin animates uProgress linearly; Niri feeds an already-eased progress. The
// Niri configs for the ported effects all use curve "ease-out-cubic".
float niri_ease(float t) { float f = t - 1.0; return f * f * f + 1.0; }

#define niri_clamped_progress clamp(niri_ease(uProgress), 0.0, 1.0)
#define niri_random_seed      uSeed
#define niri_tex              sampler

// Niri window UVs have a top-left origin; KWin's texcoord0 is bottom-left. This
// matrix maps a top-left (x, y) to the sampler coordinate (x, 1 - y), so the
// Niri expression texture2D(niri_tex, (niri_geo_to_tex * vec3(uv,1)).st) samples
// the window at the top-left UV `uv`.
const mat3 niri_geo_to_tex = mat3(1.0, 0.0, 0.0,
                                  0.0, -1.0, 0.0,
                                  0.0, 1.0, 1.0);

// --------------------------------------------------------------------- Niri body

            // Ported from gl-transitions/circleopen.glsl (MIT, gre)

            vec4 open_color(vec3 coords_geo, vec3 size_geo) {
                float p = niri_clamped_progress;
                vec2 uv = coords_geo.xy;
                float seed = niri_random_seed;

                float smoothness = 0.3;
                float SQRT_2 = 1.414213562;

                vec2 center = vec2(0.5 + (seed - 0.5) * 0.15, 0.5 + (seed * 0.7 - 0.35) * 0.15);

                float dist = SQRT_2 * distance(center, uv);
                float m = smoothstep(-smoothness, 0.0, dist - p * (1.0 + smoothness));
                float reveal = 1.0 - m;

                vec3 tc = niri_geo_to_tex * vec3(uv, 1.0);
                vec4 color = texture2D(niri_tex, tc.st);

                return color * reveal;
            }


            vec4 close_color(vec3 coords_geo, vec3 size_geo) {
                float p = niri_clamped_progress;
                vec2 uv = coords_geo.xy;
                float seed = niri_random_seed;

                float smoothness = 0.3;
                float SQRT_2 = 1.414213562;

                // Slightly randomized center
                vec2 center = vec2(0.5 + (seed - 0.5) * 0.15, 0.5 + (seed * 0.7 - 0.35) * 0.15);

                float dist = SQRT_2 * distance(center, uv);
                float m = smoothstep(-smoothness, 0.0, dist - (1.0 - p) * (1.0 + smoothness));
                float remain = 1.0 - m;

                vec3 tc = niri_geo_to_tex * vec3(uv, 1.0);
                vec4 color = texture2D(niri_tex, tc.st);

                return color * remain;
            }

// -------------------------------------------------------------------- entry point
void main() {
  vec3 coords_geo = vec3(texcoord0.x, 1.0 - texcoord0.y, 0.0);
  vec3 size_geo   = vec3(float(textureWidth), float(textureHeight), 1.0);

  vec4 c = uForOpening ? open_color(coords_geo, size_geo)
                       : close_color(coords_geo, size_geo);

  // Niri returns premultiplied-alpha color -- exactly what KWin expects.
  fragColor = c;
  fragColor = sourceEncodingToNitsInDestinationColorspace(fragColor);
  fragColor = nitsToDestinationEncoding(fragColor);
}
