#version 140

// SPDX-License-Identifier: MIT
//
// Niri -> KWin 6 (Plasma 6) compatibility shim -- desktop GL core profile.
// Auto-generated by build/generate.py. Do not edit by hand; edit the generator.
//
// The Niri open_color()/close_color() body below is used verbatim. This prelude
// emulates the Niri built-ins it references.

#include "colormanagement.glsl"

uniform sampler2D sampler;
uniform int textureWidth;
uniform int textureHeight;

uniform bool  uForOpening;   // true while a window-open animation runs
uniform float uProgress;     // linear 0 -> 1 over the animation
uniform float uSeed;      // per-animation random phase, [0, 1)

in vec2 texcoord0;
out vec4 fragColor;

// The Niri bodies call texture2D(); route it to the core-profile entry point.
#define texture2D texture

// KWin animates uProgress linearly; Niri feeds an already-eased progress. The
// Niri configs for the ported effects all use curve "ease-out-cubic".
float niri_ease(float t) { float f = t - 1.0; return f * f * f + 1.0; }

#define niri_clamped_progress clamp(niri_ease(uProgress), 0.0, 1.0)
#define niri_random_seed      uSeed
#define niri_tex              sampler

// Niri window UVs have a top-left origin; KWin's texcoord0 is bottom-left. This
// matrix maps a top-left (x, y) to the sampler coordinate (x, 1 - y), so the
// Niri expression texture2D(niri_tex, (niri_geo_to_tex * vec3(uv,1)).st) samples
// the window at the top-left UV `uv`.
const mat3 niri_geo_to_tex = mat3(1.0, 0.0, 0.0,
                                  0.0, -1.0, 0.0,
                                  0.0, 1.0, 1.0);

// --------------------------------------------------------------------- Niri body
            float gh(float n) {
                return fract(sin(n) * 43758.5453);
            }

            vec4 open_color(vec3 coords_geo, vec3 size_geo) {
                float p = niri_clamped_progress;
                vec2 uv = coords_geo.xy;

                float intensity = (1.0 - p) * (1.0 - p);

                float tick = floor(p * 60.0) + niri_random_seed * 1000.0;
                float r1 = gh(tick * 1.13);
                float r2 = gh(tick * 2.37);
                float r3 = gh(tick * 3.71);
                float r4 = gh(tick * 4.19);
                float r5 = gh(tick * 5.53);
                float r6 = gh(tick * 6.91);

                vec2 off_r = vec2(r1 - 0.5, r2 - 0.5) * intensity * 0.12;
                vec2 off_g = vec2(r3 - 0.5, r4 - 0.5) * intensity * 0.12;
                vec2 off_b = vec2(r5 - 0.5, r6 - 0.5) * intensity * 0.12;

                float slice = floor(uv.y * 20.0);
                float slice_offset = (gh(slice + tick) - 0.5) * intensity * 0.08;

                vec2 uv_r = uv + off_r + vec2(slice_offset * 0.7, 0.0);
                vec2 uv_g = uv + off_g + vec2(slice_offset * -0.5, 0.0);
                vec2 uv_b = uv + off_b + vec2(slice_offset * 0.3, 0.0);

                vec3 tc_r = niri_geo_to_tex * vec3(uv_r, 1.0);
                vec3 tc_g = niri_geo_to_tex * vec3(uv_g, 1.0);
                vec3 tc_b = niri_geo_to_tex * vec3(uv_b, 1.0);

                vec4 color;
                color.r = texture2D(niri_tex, tc_r.st).r;
                color.g = texture2D(niri_tex, tc_g.st).g;
                color.b = texture2D(niri_tex, tc_b.st).b;
                color.a = max(max(
                    texture2D(niri_tex, tc_r.st).a,
                    texture2D(niri_tex, tc_g.st).a),
                    texture2D(niri_tex, tc_b.st).a);

                float big_glitch = step(0.85, gh(tick * 0.77));
                vec2 shift = vec2((gh(tick * 1.5) - 0.5) * 0.06 * big_glitch * intensity, 0.0);
                vec3 tc_shift = niri_geo_to_tex * vec3(uv + shift, 1.0);
                vec4 shifted = texture2D(niri_tex, tc_shift.st);
                color = mix(color, shifted, big_glitch * intensity * 0.4);

                float scanline = 1.0 - sin(uv.y * size_geo.y * 3.14159) * 0.06 * intensity;
                color.rgb *= scanline;

                float alpha = smoothstep(0.0, 0.15, p);
                return color * alpha;
            }


            vec4 close_color(vec3 coords_geo, vec3 size_geo) {
                float p = niri_clamped_progress;
                vec2 uv = coords_geo.xy;

                float intensity = p * p;

                float tick = floor(p * 60.0) + niri_random_seed * 1000.0;
                float r1 = gh(tick * 1.13);
                float r2 = gh(tick * 2.37);
                float r3 = gh(tick * 3.71);
                float r4 = gh(tick * 4.19);
                float r5 = gh(tick * 5.53);
                float r6 = gh(tick * 6.91);

                vec2 off_r = vec2(r1 - 0.5, r2 - 0.5) * intensity * 0.15;
                vec2 off_g = vec2(r3 - 0.5, r4 - 0.5) * intensity * 0.15;
                vec2 off_b = vec2(r5 - 0.5, r6 - 0.5) * intensity * 0.15;

                float slice = floor(uv.y * 20.0);
                float slice_offset = (gh(slice + tick) - 0.5) * intensity * 0.12;

                vec2 uv_r = uv + off_r + vec2(slice_offset * 0.7, 0.0);
                vec2 uv_g = uv + off_g + vec2(slice_offset * -0.5, 0.0);
                vec2 uv_b = uv + off_b + vec2(slice_offset * 0.3, 0.0);

                vec3 tc_r = niri_geo_to_tex * vec3(uv_r, 1.0);
                vec3 tc_g = niri_geo_to_tex * vec3(uv_g, 1.0);
                vec3 tc_b = niri_geo_to_tex * vec3(uv_b, 1.0);

                vec4 color;
                color.r = texture2D(niri_tex, tc_r.st).r;
                color.g = texture2D(niri_tex, tc_g.st).g;
                color.b = texture2D(niri_tex, tc_b.st).b;
                color.a = max(max(
                    texture2D(niri_tex, tc_r.st).a,
                    texture2D(niri_tex, tc_g.st).a),
                    texture2D(niri_tex, tc_b.st).a);

                float big_glitch = step(0.8 - p * 0.3, gh(tick * 0.77));
                vec2 shift = vec2((gh(tick * 1.5) - 0.5) * 0.08 * big_glitch * intensity, 0.0);
                vec3 tc_shift = niri_geo_to_tex * vec3(uv + shift, 1.0);
                vec4 shifted = texture2D(niri_tex, tc_shift.st);
                color = mix(color, shifted, big_glitch * intensity * 0.5);

                float scanline = 1.0 - sin(uv.y * size_geo.y * 3.14159) * 0.08 * intensity;
                color.rgb *= scanline;

                float alpha = smoothstep(1.0, 0.6, p);
                return color * alpha;
            }

// -------------------------------------------------------------------- entry point
void main() {
  vec3 coords_geo = vec3(texcoord0.x, 1.0 - texcoord0.y, 0.0);
  vec3 size_geo   = vec3(float(textureWidth), float(textureHeight), 1.0);

  vec4 c = uForOpening ? open_color(coords_geo, size_geo)
                       : close_color(coords_geo, size_geo);

  // Niri returns premultiplied-alpha color -- exactly what KWin expects.
  fragColor = c;
  fragColor = sourceEncodingToNitsInDestinationColorspace(fragColor);
  fragColor = nitsToDestinationEncoding(fragColor);
}
